services:
  west-update:
    build: .
    volumes:
      - ./.docker-west:/workspace
      - .:/zmk-config
    working_dir: /workspace
    command: west update --fetch-opt=--filter=tree:0

  lily58-left:
    build: .
    volumes:
      - ./.docker-west:/workspace
      - .:/zmk-config
    working_dir: /workspace
    command: >
      bash -c "west build -s zmk/app -d /workspace/.build/lily58-left -b nice_nano --
      -DZMK_CONFIG=/zmk-config/config -DSHIELD=lily58_left -DZephyr_DIR=/workspace/zephyr/share/zephyr-package/cmake &&
      mkdir -p /zmk-config/firmware &&
      cp /workspace/.build/lily58-left/zephyr/zmk.uf2 /zmk-config/firmware/lily58-left.uf2"

  lily58-right:
    build: .
    volumes:
      - ./.docker-west:/workspace
      - .:/zmk-config
    working_dir: /workspace
    command: >
      bash -c "west build -s zmk/app -d /workspace/.build/lily58-right -b nice_nano --
      -DZMK_CONFIG=/zmk-config/config -DSHIELD=lily58_right -DZephyr_DIR=/workspace/zephyr/share/zephyr-package/cmake &&
      mkdir -p /zmk-config/firmware &&
      cp /workspace/.build/lily58-right/zephyr/zmk.uf2 /zmk-config/firmware/lily58-right.uf2"

  corne-left:
    build: .
    volumes:
      - ./.docker-west:/workspace
      - .:/zmk-config
    working_dir: /workspace
    command: >
      bash -c "west build -s zmk/app -d /workspace/.build/corne-left -b nice_nano_v2 --
      -DZMK_CONFIG=/zmk-config/config -DSHIELD=corne_left -DZephyr_DIR=/workspace/zephyr/share/zephyr-package/cmake &&
      mkdir -p /zmk-config/firmware &&
      cp /workspace/.build/corne-left/zephyr/zmk.uf2 /zmk-config/firmware/corne-left.uf2"

  corne-right:
    build: .
    volumes:
      - ./.docker-west:/workspace
      - .:/zmk-config
    working_dir: /workspace
    command: >
      bash -c "west build -s zmk/app -d /workspace/.build/corne-right -b nice_nano_v2 --
      -DZMK_CONFIG=/zmk-config/config -DSHIELD=corne_right -DZephyr_DIR=/workspace/zephyr/share/zephyr-package/cmake &&
      mkdir -p /zmk-config/firmware &&
      cp /workspace/.build/corne-right/zephyr/zmk.uf2 /zmk-config/firmware/corne-right.uf2"

  draw-keymaps:
    build: keymap-drawer
    volumes:
      - ./.docker-west:/west:ro
      - .:/zmk-config
    working_dir: /zmk-config
    command: >
      bash -c "
      keymap -c keymap-drawer/config.yaml parse -z config/corne.keymap  > keymap-drawer/corne.yaml  &&
      keymap -c keymap-drawer/config.yaml parse -z config/lily58.keymap > keymap-drawer/lily58.yaml &&
      keymap -c keymap-drawer/config.yaml draw  -z corne -l five_column_transform  keymap-drawer/corne.yaml  > keymap-drawer/corne.svg  &&
      keymap -c keymap-drawer/config.yaml draw  -z lily58 keymap-drawer/lily58.yaml > keymap-drawer/lily58.svg &&
      python3 keymap-drawer/fix_emoji_colors.py keymap-drawer/corne.svg keymap-drawer/lily58.svg &&
      echo Done. SVGs written to keymap-drawer/"
